version: '2.1'
services:
  api:
    restart: always
    container_name: api
    image: snailpass-server-api-image
    environment:
      - SNAILPASS_SECRET_KEY=development_env_secret_key
      - SNAILPASS_CONFIGURATION=dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/snailpass-server
    entrypoint:
      - scripts/start_dev.sh
