FROM python:3.10-slim

RUN apt-get clean \
    && apt-get -y update

RUN apt-get -y install python3-dev \
    && apt-get -y install build-essential

WORKDIR /snailpass-server
COPY ./requirements-prod.txt /snailpass-server
RUN pip install -r requirements-prod.txt

COPY . /snailpass-server

RUN chmod +x scripts/start_prod.sh

