FROM python:3.10-slim

RUN apt-get clean \
    && apt-get -y update

RUN apt-get -y install nginx \
    && apt-get -y install python3-dev \
    && apt-get -y install build-essential


WORKDIR /snailpass-rest-api
COPY . /snailpass-rest-api

RUN pip install --no-cache-dir -r requirements-prod.txt

COPY nginx.conf /etc/nginx
RUN chmod +x scripts/start_prod.sh

