version: '2.1'
services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${DEV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DEV_POSTGRES_DB}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    restart: always
    environment:
      - SNAILPASS_SECRET_KEY=${SNAILPASS_SECRET_KEY}
      - FLASK_DEBUG=dev
    image: snailpass-rest-api-image
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    entrypoint: ["python", "manage.py","runserver"]
